# Generated by Django 3.2.16 on 2022-10-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_ingredients'),
    ]

    operations = [
    ]
