# Generated by Django 3.2.16 on 2022-10-26 18:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#778899', image_field=None, max_length=18, samples=None, unique=True, verbose_name='Цвет в формате HEX'),
        ),
    ]
