# Generated by Django 3.2.16 on 2022-10-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_tag_color'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='amount_gte_1',
        ),
    ]
